% Analysis 

```{r global_options, include = FALSE}
knitr::opts_chunk$set(cache = FALSE,
                      comment = "##",
                      collapse = TRUE,
                      warning = FALSE,
                      message = FALSE)

```


# Libraries

To reproduce the examples of this material, the R packages the following packages are needed.

```{r warning=FALSE, message=FALSE}
library(rio)
library(tidyverse)
library(pliman)
set_wd_here("data/flax")
```

# juntas
```{r}
img <- image_import("junto.png")

seg <- 
image_segment(img*2,
              index = "G",
              fill_hull = TRUE,
              # filter = 2,
              col_background = "white")
image_export(seg, "junto2.png")
```

# ex 1
```{r}
imgs <- image_import("img3.jpg")

cinza <- image_index(imgs, "R/(G/B)")
image_export(cinza$`R/(G/B)`, "cinza.png")
binaria <- image_binary(imgs, "R/(G/B)", filter = 3)
image_export(binaria$`R/(G/B)`, "binaria.png")
seg1 <- image_segment(imgs, index = "R/(G/B)", filter = 3)
image_export(seg1, "segmentada.png")


cinza2 <- image_index(seg1, "B-R")
binaria2 <- image_binary(seg1, "B-R")
seg2 <- image_segment(seg1, index = "B-R")


res <- 
  analyze_objects(imgs,
                  reference = TRUE,
                  reference_area = 19.8,
                    back_fore_index = "R/(G/B)",
                  marker = "length",
                  marker_size = 2,
                  contour_size = 2,
                  # save_image = TRUE,
                  watershed = FALSE)
```



# coloração
```{r}
tmp <- imgs$img2.jpg |> image_resize(50)
res <- 
  analyze_objects(tmp,
                  index = "B",
                  filter = 2,
                  # contour_size = 2,
                  # save_image = TRUE,
                  watershed = FALSE,
                  marker = "id",
                  object_index = "DGCI",
                  dir_processed = "data/flax")

ind <- summary_index(res,
                     index = "DGCI",
                     cut_point = 0.5)

barplot(t(ind$within_id[,6:7]) |> as.matrix(),
        legend = c("DGCI < 0.5", "DGCI > 0.5"))

plot(tmp)
# plot_contour(cont, col = "red")
plot_measures(res,
              measure = "R",
              # size = 0.6,
              id = ind$ids)

```





# Section info
```{r}
sessionInfo()
```

